version: 0.1

environment_variables:
  plaintext:
    NODE_ENV: "development"
phases:
  install:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test
      - npm run clean
  post_build:
    commands:
      - echo Build completed [`date`]
